apiVersion: v1
kind: Secret
metadata:
  name: fusion-secrets
  namespace: fusion
type: Opaque
data:
  # JWT Secrets (base64 encoded)
  JWT_SECRET: OTg4OTNhMjBmYjg3MDRmMzgzNjdlMmU3MGFlMmM4MGE3ZGMxMzg0M2YxODkwYzc1MTIyOGQ5YWJmNWYwMjQyMQ==
  REFRESH_TOKEN_SECRET: MzY3YWFlZjZkMGJjMjI4ZjUzOTc0MTBjZmU5NmU0MTRlZTY3YzBjODkzNWI4MTYwYjhkMzA4YjE3NDgzZTU5NA==
  
  # SendGrid API Key
  SENDGRID_API_KEY: U0cuUDEtem5LT0RTeFd0QlBwc1pORVdUdy5Ea0ZQTjJFNjNyRDZPX2pzUmhVakE1Qm5xM19UbGxnLUktYU5XRVdWZm9V
  SENDGRID_FROM_EMAIL: YW1hbGFyaXlhLnRob21hcyt2MTNAZHJLYW1zdGVjaG5vbG9naWVzLmNvbQ==
  
  # Crypto Secret
  CRYPTO_SECRET_KEY: ZnVzaW9uX05vZGVAIQ==
  
  # AWS S3 Credentials
  ACCESS_KEY_ID: QUtJQTQ0REdHWlpYWjZSNk9PWU0=
  SECRET_ACCESS_KEY: R1cwdHNkYlhBWW5FazgwQi8zQ2ZBSENTZENWOS9hUVV6c3VoVUh5bA==
  REGION: dXMtZWFzdC0y
  BUCKET_NAME: ZHJlYW1zdGVjaG5vbG9naWVzMjAyNQ==
  BUCKET_FOLDER: ZnVzaW9uX25vZGVfZGV2
  
  # Stripe Keys
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVJWZWE4UnZqazBsY1I0ZUN2TWlvWjZaa1VGdEM4ZGZvcGwwRDBRa1RJNVFMMG44NU5VT3BXN2dDeWtNc3pzWGVlTEpTeGN6bFE4cU1udnV5NnNhSzh1MDBnU3dOckJCQw==
  STRIPE_WEBHOOK_SECRET: d2hzZWNfU3p4VW5JcmMzT1phZHdDaERFV3lCUTd4UUw0d05TejY=
  
  # Super Admin Password
  PASSWORD: RHJlYW1zQDk5
  
  # Exchange Rate API Key
  EXCHANGE_RATE_API_KEY: MjJiZWJhZjY4YWJiZmRhYTk1NzI2YmI3
  
  # Twilio Credentials
  TWILIO_ACCOUNT_SID: QUMyYWI0ZTM1MmRlOWYzM2IyYjE3YzNmYWFjZTJlZDgyMg==
  TWILIO_AUTH_TOKEN: ZDljYWJlMGJjMWM5ZTBkYTQwNTgwM2YxY2E1YzYwOTE=
  TWILIO_API_KEY: U0syMTVjNWUzNWMzYmNlNjc4YzlhMjA3YWUzNzZhOWNkNw==
  TWILIO_API_SECRET: d25XdGd4NExvVzM5clhsSk5LSHlJa0tRUm44M0FXZzA=