const sampleData = {
  Purchase: [
    {
      sno:1,
      userId: "Jhone",
      companyId: "classic",
      date: new Date("2025-06-26"),
      vendor: "ABC Pvt Ltd",
      vendorSO: "VSO-2025-001",
      description: "Purchase order for electronics",
      extDescription: "Urgent order - handle carefully",
      internalComment: "Internal note: confirm stock",
      currency: "USD",
      rep: "John Doe",
      terms: "Net 30",
      // condition: "New",
      shipDate: new Date("2025-06-28"),
      address: "123, Mount Road, Chennai",
      country: "India",
      state: "Tamil Nadu",
      city: "Chennai",
      wareHouse: "Chennai WH",
      tax: "GST 18%",
      status: "Open",
      receive: "In Transit",
      extendedCost: 200,
      freight: 100,
      extraCost: 50,
      subTotal: 200,
      total: 270,
    },
    {
      sno:2,
      userId: "Danny",
      companyId: "company ABC",
      date: new Date("2025-06-27"),
      vendor: "XYZ Pvt Ltd",
      vendorSO: "VSO-2025-002",
      description: "Purchase order for appliances",
      extDescription: "Handle gently - some items are used",
      internalComment: "Internal note: check warranty",
      currency: "USD",
      rep: "Jane Smith",
      terms: "Net 45",
      // condition: "Used",
      shipDate: new Date("2025-06-29"),
      address: "456, Marine Drive, Mumbai",
      country: "India",
      state: "Maharashtra",
      city: "Mumbai",
      wareHouse: "Mumbai WH",
      tax: "GST 12%",
      status: "Open",
      receive: "In Transit",
      extendedCost: 150,
      freight: 80,
      extraCost: 30,
      subTotal: 150,
      total: 175,
    },
  ],
  Items: [
    {
      pSno:1,
      item: "Item A",
      quantity: 1,
      purchaseCostCAD: 100,
      purchaseCostUSD: 100,
      extendedCostCAD: 100,
      extendedCostUSD: 100,
      serialNumber: "1234567890",
      condition: "New",
    },
    {
      pSno:2,
      item: "Item B",
      quantity: 2,
      purchaseCostCAD: 120,
      purchaseCostUSD: 120,
      extendedCostCAD: 240,
      extendedCostUSD: 240,
      serialNumber: "0987654321",
      condition: "New",
    },
    {
      pSno:1,
      item: "Item C",
      quantity: 1,
      purchaseCostCAD: 80,
      purchaseCostUSD: 80,
      extendedCostCAD: 80,
      extendedCostUSD: 80,
      serialNumber: "1122334455",
      condition: "Used",
    },
  ],
};

export { sampleData };
