import { body } from "express-validator";
import mongoose from "mongoose";

export const validateCreateSale = [
  body("date").notEmpty().withMessage("Date is required").isISO8601().withMessage("Date must be a valid ISO date"),
  body("client").notEmpty().withMessage("client is required").custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid vendor id"),
  body("currency").notEmpty().withMessage("Currency is required").custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid currency id"),
  body("rep").notEmpty().withMessage("Rep is required").custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid rep id"),
  body("terms").notEmpty().withMessage("Terms is required").custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid terms id"),
  body("country").optional().custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid country id"),
  body("state").optional().custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid state id"),
  body("city").optional().custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid city id"),
  body("tax").notEmpty().withMessage("Tax is required").custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid tax id"),
  // body("status").notEmpty().withMessage("Status is required").isIn(["Open", "Approved", "Rejected", "Cancelled"]).withMessage("Invalid status value"),
  // body("saleType").notEmpty().withMessage("saleType is required").isIn(["sp", "so"]).withMessage("saleType must be 'sp' or 'so'"),
  // body("isActive").notEmpty().withMessage("isActive is required").isBoolean().withMessage("isActive must be boolean"),
  // body("isConverted").notEmpty().withMessage("isConverted is required").isBoolean().withMessage("isConverted must be boolean"),
  body("items").isArray({ min: 1 }).withMessage("At least one item is required"),
  body("items.*.item").notEmpty().withMessage("Item is required").custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid item id"),
  body("items.*.quantity").notEmpty().withMessage("Quantity is required").isNumeric().withMessage("Quantity must be a number"),
  body("items.*.condition").notEmpty().withMessage("Condition is required").custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid condition id"),
  body("items.*.saleCostCAD").optional().isNumeric().withMessage("saleCostCAD must be a number"),
  body("items.*.saleCostUSD").optional().isNumeric().withMessage("saleCostUSD must be a number"),
  body("items.*.extendedCostCAD").optional().isNumeric().withMessage("extendedCostCAD must be a number"),
  body("items.*.extendedCostUSD").optional().isNumeric().withMessage("extendedCostUSD must be a number"),
  body("items.*.serialNumber").optional().isString().withMessage("serialNumber must be a string"),
  body("items.*.warehouseId").notEmpty().withMessage("Warehouse is required").custom(value => mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid warehouse id"),
  // Optional fields
  body("spId").optional().custom(value => !value || mongoose.Types.ObjectId.isValid(value)).withMessage("Invalid spId"),
  body("sp").optional().isString().withMessage("sp must be a string"),
  body("so").optional().isString().withMessage("so must be a string"),
  body("description").optional().isString(),
  body("extDescription").optional().isString(),
  body("internalComment").optional().isString(),
  body("commentToVendor").optional().isString(),
  body("vendorSO").optional().isString(),
  body("address").optional().isString(),
  body("shipDate").optional().isISO8601().withMessage("shipDate must be a valid ISO date"),
  body("extendedCost").optional().isNumeric(),
  body("freight").optional().isNumeric(),
  body("extraCost").optional().isNumeric(),
  body("subTotal").optional().isNumeric(),
  body("total").optional().isNumeric(),
];
